spring.datasource.url=jdbc:postgresql://ep-long-resonance-ahy8a14m-pooler.c-3.us-east-1.aws.neon.tech/neondb?sslmode=require

spring.datasource.username=neondb_owner

spring.datasource.password=npg_LJT8i7hkpRWK

spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

server.port=8080